# Generated by Django 5.2.10 on 2026-02-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0040_customfield_name_de_customfield_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='visible_by_patient',
            field=models.BooleanField(default=True, verbose_name='visible by patient'),
        ),
    ]
