# Generated by Django 5.2.11 on 2026-03-13 21:23

import core.storage
import django_clamd.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0043_request_created_at_request_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.storage.TenantUploadTo('messages_attachment'), validators=[django_clamd.validators.validate_file_infection], verbose_name='attachment'),
        ),
    ]
