# Generated by Django 5.2.11 on 2026-03-24 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0044_alter_message_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(verbose_name='last read at')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='consultations.consultation', verbose_name='consultation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_read_statuses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'consultation read status',
                'verbose_name_plural': 'consultation read statuses',
                'unique_together': {('consultation', 'user')},
            },
        ),
    ]
