# Generated by Django 5.2.11 on 2026-03-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0045_consultationreadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='name_it',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='queue',
            name='name_es',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='queue',
            name='name_it',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='reason',
            name='name_es',
            field=models.CharField(null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='reason',
            name='name_it',
            field=models.CharField(null=True, verbose_name='name'),
        ),
    ]
