import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';
import localeDe from '@angular/common/locales/de';
import localeEs from '@angular/common/locales/es';
import localeIt from '@angular/common/locales/it';
import { bootstrapApplication } from '@angular/platform-browser';

registerLocaleData(localeFr);
registerLocaleData(localeDe);
registerLocaleData(localeEs);
registerLocaleData(localeIt);
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules, withComponentInputBinding } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { register } from 'swiper/element/bundle';
import { provideHttpClient, withInterceptorsFromDi, HTTP_INTERCEPTORS } from '@angular/common/http';
import { APP_INITIALIZER } from '@angular/core';
import { AuthService } from './app/core/services/auth.service';
import { importProvidersFrom, isDevMode } from '@angular/core';
import { provideServiceWorker } from '@angular/service-worker';
import { provideTranslateService } from '@ngx-translate/core';
import { provideTranslateHttpLoader } from '@ngx-translate/http-loader';
import { AuthInterceptor } from './app/core/interceptors/auth.interceptor';
import { IonicStorageModule } from '@ionic/storage-angular';
import { addIcons } from 'ionicons';
import {
  homeOutline,
  homeSharp,
  calendarOutline,
  calendarSharp,
  calendar,
  notificationsOutline,
  notificationsSharp,
  personOutline,
  personSharp,
  medicalOutline,
  medicalSharp,
  documentTextOutline,
  documentTextSharp,
  documentText,
  medkitOutline,
  medkitSharp,
  medkit,
  starOutline,
  star,
  starSharp,
  timeOutline,
  timeSharp,
  checkmarkCircle,
  checkmarkCircleOutline,
  mailOutline,
  mailSharp,
  mail,
  informationCircle,
  informationCircleOutline,
  warningOutline,
  warningSharp,
  trashOutline,
  trashSharp,
  notificationsOffOutline,
  chevronBackOutline,
  chevronForwardOutline,
  eyeOutline,
  eyeOffOutline,
  logoGoogle,
  logoFacebook,
  logoApple,
  fitness,
  lockClosedOutline,
  settingsOutline, peopleOutline, bodyOutline, heartOutline, pulseOutline, fitnessOutline, locationOutline,
  videocamOutline, cardOutline, closeCircle, addCircleOutline, refresh, cameraOutline, logOutOutline, helpCircleOutline,
  callOutline, barbellOutline, resizeOutline, waterOutline, moonOutline, bulbOutline, chatbubblesOutline, flaskOutline,
  pricetagOutline, trash, shareOutline, arrowUp, downloadOutline, cloudUploadOutline, schoolOutline, briefcaseOutline,
  mic, micOff, videocam, videocamOff, call, volumeHigh, volumeMute, desktopOutline,
  cameraReverseOutline, ellipse, alertCircle, alertCircleOutline, arrowBackOutline, clipboardOutline, addOutline,
  hourglassOutline, ellipsisVerticalOutline, chatbubbleEllipsesOutline, closeCircleOutline,
  sendOutline, attachOutline, imageOutline, wifiOutline, cloudOfflineOutline, closeOutline,
  atOutline, createOutline, close, shieldCheckmarkOutline, keypadOutline, checkmarkOutline,
  globeOutline, chevronDownOutline, flashOutline, mailOpenOutline
} from 'ionicons/icons';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';

register();

addIcons({
  'home-outline': homeOutline,
  'home-sharp': homeSharp,
  'calendar-outline': calendarOutline,
  'calendar-sharp': calendarSharp,
  'calendar': calendar,
  'notifications-outline': notificationsOutline,
  'notifications-sharp': notificationsSharp,
  'person-outline': personOutline,
  'person-sharp': personSharp,
  'medical-outline': medicalOutline,
  'medical-sharp': medicalSharp,
  'document-text-outline': documentTextOutline,
  'document-text-sharp': documentTextSharp,
  'document-text': documentText,
  'medkit-outline': medkitOutline,
  'medkit-sharp': medkitSharp,
  'medkit': medkit,
  'star-outline': starOutline,
  'star': star,
  'star-sharp': starSharp,
  'time-outline': timeOutline,
  'time-sharp': timeSharp,
  'checkmark-circle': checkmarkCircle,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'mail-outline': mailOutline,
  'mail-sharp': mailSharp,
  'mail': mail,
  'information-circle': informationCircle,
  'information-circle-outline': informationCircleOutline,
  'warning-outline': warningOutline,
  'warning-sharp': warningSharp,
  'trash-outline': trashOutline,
  'trash-sharp': trashSharp,
  'notifications-off-outline': notificationsOffOutline,
  'chevron-back-outline': chevronBackOutline,
  'chevron-forward-outline': chevronForwardOutline,
  'eye-outline': eyeOutline,
  'eye-off-outline': eyeOffOutline,
  'logo-google': logoGoogle,
  'logo-facebook': logoFacebook,
  'logo-apple': logoApple,
  'fitness': fitness,
  'lock-closed-outline': lockClosedOutline,
  'settings-outline': settingsOutline,
  'people-outline': peopleOutline,
  'body-outline': bodyOutline,
  'heart-outline': heartOutline,
  'pulse-outline': pulseOutline,
  'fitness-outline': fitnessOutline,
  'location-outline': locationOutline,
  'videocam-outline': videocamOutline,
  'card-outline': cardOutline,
  'close-circle': closeCircle,
  'add-circle-outline': addCircleOutline,
  'refresh': refresh,
  'camera-outline': cameraOutline,
  'log-out-outline': logOutOutline,
  'help-circle-outline': helpCircleOutline,
  'call-outline': callOutline,
  'barbell-outline': barbellOutline,
  'resize-outline': resizeOutline,
  'water-outline': waterOutline,
  'moon-outline': moonOutline,
  'bulb-outline': bulbOutline,
  'chatbubble-outline': chatbubblesOutline,
  'chatbubbles-outline': chatbubblesOutline,
  'flask-outline': flaskOutline,
  'pricetag-outline': pricetagOutline,
  'trash': trash,
  'share-outline': shareOutline,
  'arrow-up': arrowUp,
  'download-outline': downloadOutline,
  'cloud-upload-outline': cloudUploadOutline,
  'school-outline': schoolOutline,
  'briefcase-outline': briefcaseOutline,
  'mic': mic,
  'mic-off': micOff,
  'videocam': videocam,
  'videocam-off': videocamOff,
  'call': call,
  'volume-high': volumeHigh,
  'volume-mute': volumeMute,
  'desktop-outline': desktopOutline,
  'camera-reverse-outline': cameraReverseOutline,
  'ellipse': ellipse,
  'alert-circle': alertCircle,
  'arrow-back-outline': arrowBackOutline,
  'clipboard-outline': clipboardOutline,
  'add-outline': addOutline,
  'hourglass-outline': hourglassOutline,
  'ellipsis-vertical-outline': ellipsisVerticalOutline,
  'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
  'close-circle-outline': closeCircleOutline,
  'send-outline': sendOutline,
  'attach-outline': attachOutline,
  'image-outline': imageOutline,
  'wifi-outline': wifiOutline,
  'cloud-offline-outline': cloudOfflineOutline,
  'close-outline': closeOutline,
  'close': close,
  'at-outline': atOutline,
  'create-outline': createOutline,
  'alert-circle-outline': alertCircleOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'keypad-outline': keypadOutline,
  'checkmark-outline': checkmarkOutline,
  'globe-outline': globeOutline,
  'chevron-down-outline': chevronDownOutline,
  'flash-outline': flashOutline,
  'mail-open-outline': mailOpenOutline,
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular({ animated: false }),
    provideRouter(routes,
      withPreloading(PreloadAllModules),
      withComponentInputBinding()
    ),
    provideHttpClient(withInterceptorsFromDi()),
    { provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true },
    {
      provide: APP_INITIALIZER,
      useFactory: (auth: AuthService) => () => auth.initConfig(),
      deps: [AuthService],
      multi: true,
    },
    importProvidersFrom(IonicStorageModule.forRoot()),
    provideTranslateService({
      loader: provideTranslateHttpLoader({
        prefix: './assets/i18n/',
        suffix: '.json',
        useHttpBackend: true,
      }),
      fallbackLang: 'en',
      lang: 'en',
    }),
    provideServiceWorker('custom-sw.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000',
    }),
  ]
}).catch(err => console.log(err));
