export enum RoutePaths {
  AUTH = 'auth',
  USER = 'app',
  CONSULTATIONS = 'consultations',
  CONSULTATION_DETAIL = 'consultations/:id',
  DASHBOARD = 'dashboard',
  PROFILE = 'profile',
  PATIENTS = 'patients',
  PATIENT_DETAIL = 'patients/:id',
  APPOINTMENTS = 'appointments',
  AVAILABILITY = 'availability',
  VERIFY_INVITE = 'verify-invite',
  CONFIRM_PRESENCE = 'confirm-presence',
  CGU = 'terms',
  ONBOARDING = 'onboarding',
}
