import {
  APP_INITIALIZER,
  ApplicationConfig,
  isDevMode,
  provideBrowserGlobalErrorListeners,
  provideZoneChangeDetection,
} from '@angular/core';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideServiceWorker } from '@angular/service-worker';
import { provideRouter } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import {
  provideHttpClient,
  withFetch,
  withInterceptors,
} from '@angular/common/http';

import { provideTranslateService } from '@ngx-translate/core';
import { provideTranslateHttpLoader } from '@ngx-translate/http-loader';

import { routes } from './app.routes';
import { provideEnvironmentNgxMask } from 'ngx-mask';
import { provideIcons } from '@ng-icons/core';
import {
  heroCalendar,
  heroUser,
  heroUsers,
  heroVideoCamera,
  heroCamera,
  heroMicrophone,
  heroPhone,
  heroEye,
  heroEyeSlash,
  heroCheck,
  heroXMark,
  heroPlus,
  heroMagnifyingGlass,
  heroPencil,
  heroTrash,
  heroGlobeAlt,
  heroChevronDown,
  heroChevronLeft,
  heroChevronRight,
  heroArrowLeft,
  heroArrowRight,
  heroArrowDown,
  heroArrowUp,
  heroArrowRightOnRectangle,
  heroSquares2x2,
  heroDocumentText,
  heroClock,
  heroCheckCircle,
  heroXCircle,
  heroExclamationCircle,
  heroExclamationTriangle,
  heroEnvelope,
  heroUserCircle,
  heroPause,
  heroSpeakerWave,
  heroSpeakerXMark,
  heroUserPlus,
  heroCalendarDays,
  heroInformationCircle,
  heroBars3,
  heroPaperAirplane,
  heroBell,
  heroMinus,
  heroHeart,
  heroChartBar,
  heroScale,
  heroPaperClip,
  heroPhoto,
  heroShieldCheck,
  heroLink,
  heroClipboard,
} from '@ng-icons/heroicons/outline';
import {
  lucideVideoOff,
  lucideMicOff,
  lucidePhoneOff,
  lucideCameraOff,
  lucideLayoutDashboard,
  lucideSettings,
  lucideMinimize2,
  lucideMaximize2,
  lucideScreenShare,
  lucideScreenShareOff,
  lucideMessageSquare,
  lucideStethoscope,
  lucideSparkles,
  lucideCircleDot,
  lucideSquare,
} from '@ng-icons/lucide';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { Auth } from './core/services/auth';

export const appConfig: ApplicationConfig = {
  providers: [
    provideEnvironmentNgxMask(),
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideAnimations(),
    provideRouter(routes),
    provideIcons({
      heroCalendar,
      heroUser,
      heroUsers,
      heroVideoCamera,
      heroCamera,
      heroMicrophone,
      heroPhone,
      heroEye,
      heroEyeSlash,
      heroCheck,
      heroXMark,
      heroPlus,
      heroMagnifyingGlass,
      heroPencil,
      heroTrash,
      heroGlobeAlt,
      heroChevronDown,
      heroChevronLeft,
      heroChevronRight,
      heroArrowLeft,
      heroArrowRight,
      heroArrowDown,
      heroArrowUp,
      heroArrowRightOnRectangle,
      heroSquares2x2,
      heroDocumentText,
      heroClock,
      heroCheckCircle,
      heroXCircle,
      heroExclamationCircle,
      heroExclamationTriangle,
      heroEnvelope,
      heroUserCircle,
      heroPause,
      heroSpeakerWave,
      heroSpeakerXMark,
      heroUserPlus,
      heroCalendarDays,
      heroInformationCircle,
      heroBars3,
      heroPaperAirplane,
      heroBell,
      heroMinus,
      heroHeart,
      heroChartBar,
      heroScale,
      heroPaperClip,
      heroPhoto,
      heroShieldCheck,
      heroLink,
      heroClipboard,
      lucideVideoOff,
      lucideMicOff,
      lucidePhoneOff,
      lucideCameraOff,
      lucideLayoutDashboard,
      lucideSettings,
      lucideMinimize2,
      lucideMaximize2,
      lucideScreenShare,
      lucideScreenShareOff,
      lucideMessageSquare,
      lucideStethoscope,
      lucideSparkles,
      lucideCircleDot,
      lucideSquare,
    }),
    provideServiceWorker('custom-sw.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000',
    }),
    provideHttpClient(withFetch(), withInterceptors([authInterceptor])),
    {
      provide: APP_INITIALIZER,
      useFactory: (auth: Auth) => () => firstValueFrom(auth.getOpenIDConfig()),
      deps: [Auth],
      multi: true,
    },
    provideTranslateService({
      loader: provideTranslateHttpLoader({
        prefix: './i18n/',
        suffix: '.json',
        useHttpBackend: true,
      }),
      fallbackLang: 'en',
      lang: 'en',
    }),
  ],
};
