# Generated by Django 5.2.11 on 2026-02-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0043_message_generic_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingprovider',
            name='name',
            field=models.CharField(choices=[('clickatel', 'Clickatel SMS'), ('email', 'Email over Django SMTP'), ('ovh', 'OVH SMS'), ('swisscom', 'Swisscom SMS'), ('twilio_sms', 'Twilio SMS'), ('twilio_whatsapp', 'Twilio WhatsApp')], max_length=20, verbose_name='name'),
        ),
    ]
