# Generated by Django 5.2.11 on 2026-02-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0045_templatevalidation_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatevalidation',
            name='event_type',
            field=models.CharField(choices=[('appointment_first_reminder', 'First reminder about appointment'), ('appointment_last_reminder', "Last reminder when it's time to join appointment"), ('invitation_to_appointment', 'Message sent to participant with invitation to join a consultation at a later time'), ('appointment_cancelled', 'Message sent to participant when appointment is cancelled'), ('appointment_updated', 'Message sent to participant when appointment date and time is updated'), ('your_authentication_code', 'Message sent to participant containing their authentication code'), ('new_message_notification', 'Notification sent when a new message is posted in a consultation'), ('email_verification', 'Message sent to user to verify their email address after registration'), ('reset_password', 'Notification sent user request to change password')], help_text='The template event type to validate', max_length=100, verbose_name='event type'),
        ),
    ]
