# Generated by Django 5.2.10 on 2026-02-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0046_alter_templatevalidation_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatevalidation',
            name='content_hash',
            field=models.CharField(blank=True, help_text='MD5 hash of template content at last validation submission', max_length=32),
        ),
    ]
