# Generated by Django 5.2.10 on 2026-02-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0047_templatevalidation_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingprovider',
            name='name',
            field=models.CharField(choices=[('clickatel', 'Clickatel SMS'), ('email', 'Email over Django SMTP'), ('ovh', 'OVH SMS'), ('swisscom', 'Swisscom SMS'), ('twilio_sms', 'Twilio SMS'), ('twilio_whatsapp', 'Twilio WhatsApp'), ('webpush', 'Web Push (VAPID)')], max_length=20, verbose_name='name'),
        ),
    ]
