# Generated by Django 5.2.11 on 2026-03-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0048_alter_messagingprovider_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagingprovider',
            unique_together=set(),
        ),
    ]
