# Generated by Django 5.2.11 on 2026-03-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0049_alter_messagingprovider_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='template_system_name',
            field=models.CharField(blank=True, choices=[('appointment_first_reminder', 'First reminder about appointment'), ('appointment_last_reminder', "Last reminder when it's time to join appointment"), ('invitation_to_appointment', 'Message sent to participant with invitation to join a consultation at a later time'), ('appointment_cancelled', 'Message sent to participant when appointment is cancelled'), ('appointment_updated', 'Message sent to participant when appointment date and time is updated'), ('your_authentication_code', 'Message sent to participant containing their authentication code'), ('new_message_notification', 'Notification sent when a new message is posted in a consultation'), ('email_verification', 'Message sent to user to verify their email address after registration'), ('reset_password', 'Notification sent user request to change password'), ('consultation_assigned', 'Notification sent to patient when a consultation is assigned to them')], null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='event_type',
            field=models.CharField(choices=[('appointment_first_reminder', 'First reminder about appointment'), ('appointment_last_reminder', "Last reminder when it's time to join appointment"), ('invitation_to_appointment', 'Message sent to participant with invitation to join a consultation at a later time'), ('appointment_cancelled', 'Message sent to participant when appointment is cancelled'), ('appointment_updated', 'Message sent to participant when appointment date and time is updated'), ('your_authentication_code', 'Message sent to participant containing their authentication code'), ('new_message_notification', 'Notification sent when a new message is posted in a consultation'), ('email_verification', 'Message sent to user to verify their email address after registration'), ('reset_password', 'Notification sent user request to change password'), ('consultation_assigned', 'Notification sent to patient when a consultation is assigned to them')], help_text='Unique identifier for the template', max_length=100, unique=True, verbose_name='system name'),
        ),
        migrations.AlterField(
            model_name='templatevalidation',
            name='event_type',
            field=models.CharField(choices=[('appointment_first_reminder', 'First reminder about appointment'), ('appointment_last_reminder', "Last reminder when it's time to join appointment"), ('invitation_to_appointment', 'Message sent to participant with invitation to join a consultation at a later time'), ('appointment_cancelled', 'Message sent to participant when appointment is cancelled'), ('appointment_updated', 'Message sent to participant when appointment date and time is updated'), ('your_authentication_code', 'Message sent to participant containing their authentication code'), ('new_message_notification', 'Notification sent when a new message is posted in a consultation'), ('email_verification', 'Message sent to user to verify their email address after registration'), ('reset_password', 'Notification sent user request to change password'), ('consultation_assigned', 'Notification sent to patient when a consultation is assigned to them')], help_text='The template event type to validate', max_length=100, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='templatevalidation',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('outdated', 'Outdated'), ('unused', 'Unused')], default='created', help_text='Current validation status', max_length=20, verbose_name='status'),
        ),
    ]
