# Generated by Django 5.2.11 on 2026-03-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0050_alter_message_template_system_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_content_es',
            field=models.TextField(help_text='Jinja2 template for message content, use {{ obj }} to get object attributes', null=True, verbose_name='template text'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_content_html_es',
            field=models.TextField(blank=True, help_text='Jinja2 template for message content in html, use {{ obj }} to get object attributes', null=True, verbose_name='template html'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_content_html_it',
            field=models.TextField(blank=True, help_text='Jinja2 template for message content in html, use {{ obj }} to get object attributes', null=True, verbose_name='template html'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_content_it',
            field=models.TextField(help_text='Jinja2 template for message content, use {{ obj }} to get object attributes', null=True, verbose_name='template text'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_subject_es',
            field=models.CharField(blank=True, help_text='Jinja2 template for message subject', max_length=500, null=True, verbose_name='template subject'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_subject_it',
            field=models.CharField(blank=True, help_text='Jinja2 template for message subject', max_length=500, null=True, verbose_name='template subject'),
        ),
    ]
