# Generated by Django 5.2.11 on 2026-02-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_is_practitioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True, help_text="Whether this is the user's first login"),
        ),
    ]
