# Generated by Django 5.2.10 on 2026-02-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_is_first_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='logo_large',
            new_name='logo_color',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='logo_small',
            new_name='logo_white',
        ),
        migrations.AddField(
            model_name='organisation',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='organisations/'),
        ),
    ]
