# Generated by Django 5.2.10 on 2026-02-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_logo_large_organisation_logo_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='footer',
            new_name='footer_patient',
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_practitioner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
