# Generated by Django 5.2.10 on 2026-02-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_rename_footer_organisation_footer_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='primary_color',
            new_name='primary_color_patient',
        ),
        migrations.AddField(
            model_name='organisation',
            name='primary_color_practitioner',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
