# Generated by Django 5.2.10 on 2026-02-27 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_rename_primary_color_organisation_primary_color_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='primary_color_patient',
            field=models.CharField(default='#0891b2', max_length=7),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='primary_color_practitioner',
            field=models.CharField(default='#0891b2', max_length=7),
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(help_text='Client public key for encryption', max_length=200)),
                ('auth', models.CharField(help_text='Client auth secret', max_length=200)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpush_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'web push subscription',
                'verbose_name_plural': 'web push subscriptions',
            },
        ),
    ]
