# Generated by Django 5.2.11 on 2026-03-13 21:23

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_organisation_primary_color_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.TenantUploadTo('organisations')),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo_color',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.TenantUploadTo('organisations')),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo_white',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.TenantUploadTo('organisations')),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.TenantUploadTo('users')),
        ),
    ]
