# Generated by Django 5.2.11 on 2026-03-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_organisation_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone_number',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
