# Generated by Django 5.2.11 on 2026-03-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='term',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='content_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='name_es',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='name_it',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian')], help_text='Preferred language for the user interface', max_length=10, null=True),
        ),
    ]
