# Generated by Django 5.2.11 on 2026-03-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_speciality_name_es_speciality_name_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='login_text_patient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_practitioner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
