# Generated by Django 5.2.11 on 2026-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_organisation_login_text_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='footer_patient_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_patient_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_patient_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_patient_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_patient_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_practitioner_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_practitioner_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_practitioner_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_practitioner_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='footer_practitioner_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_patient_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_patient_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_patient_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_patient_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_patient_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_practitioner_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_practitioner_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_practitioner_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_practitioner_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='login_text_practitioner_it',
            field=models.TextField(blank=True, null=True),
        ),
    ]
